(TeX-add-style-hook "script"
 (lambda ()
    (LaTeX-add-environments
     "theorem"
     "lemma"
     "definition"
     "modellproblem")
    (LaTeX-add-labels
     "sec:motiv-und-einl"
     "eq:1"
     "sec:das-stokes-problem"
     "sec:schw-form-des"
     "problem:1"
     "eq:2"
     "eq:3"
     "sec:exist-und-eind"
     "eq:29"
     "eq:30"
     "sec:cr-diskr-und"
     "sec:motivation"
     "eq:31"
     "sec:beschr-der-diskr"
     "al:2"
     "eq:10"
     "problem:3"
     "eq:11"
     "eq:12"
     "sec:stabilitat-der-cr"
     "def:1"
     "eq:14"
     "thm:3"
     "def:2"
     "lem:1"
     "eq:16"
     "eq:17"
     "align:2"
     "eq:18"
     "sec:medius-analyse-der"
     "thm:4"
     "eq:19"
     "sec:konf-begl"
     "def:3"
     "lem:2"
     "sec:beweis-der-best"
     "eq:21"
     "eq:20"
     "eq:22"
     "al:1"
     "eq:23"
     "eq:24"
     "eq:25"
     "eq:26"
     "eq:27"
     "eq:28")
    (TeX-add-symbols
     '("set" 1)
     '("scpr" 2)
     '("hnorm" 1)
     '("norm" 1)
     '("vnorm" 1)
     '("J" 1)
     "real"
     "ubold"
     "fbold"
     "Hzero"
     "Ltwo"
     "crfem"
     "czero"
     "mesh"
     "edges"
     "nodes"
     "dx"
     "black"
     "blue"
     "red")
    (TeX-run-style-hooks
     "esint"
     "xcolor"
     "draftwatermark"
     "bbold"
     "enumitem"
     "amsthm"
     "amssymb"
     "mathtools"
     ""
     "inputenc"
     "utf8"
     "latex2e"
     "scrartcl10"
     "scrartcl"
     "a4paper")))

